name: Run Chromium Pro Setup
on: workflow_dispatch

jobs:
  run-browser-pro:
    runs-on: ubuntu-latest
    steps:
      - name: Start Chromium Container
        run: |
          docker run -d \
            --name=chromium \
            --privileged \
            --network host \
            --security-opt seccomp=unconfined \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Etc/UTC \
            --shm-size="2gb" \
            lscr.io/linuxserver/chromium:latest

      - name: Wait for Chromium boot
        run: sleep 10

      - name: Start Tmate Tunnel
        uses: mxschmitt/action-tmate@v3
